name: AndroidBuild
on:
  pull_request :
    branches : [ master ]
  push :
    branches : [ master ]

job:
  build:
    runs-on : macOS-latest
    steps:
      - name : Checkout
        uses: actions/checkout@v4.1.7

      - name : Setup Java JDK
        uses: actions/setup-java@v4.2.2

      - name : Build with Gradle
        run : ./gradlew build

      - name: Upload a Build Artifac
        uses: actions/upload-artifact@v3.2.1-node20
        with:
          name: AndroidCICD.apk
          path: app/build/output/apk/debug/app-debug-apk

